### ISSUE TITLE
Enable SSL needs management

### ISSUE THREAD

**Issue by JinsPeter** [petabridge/lighthouse#102]
We are using this project as the lighthouse seed node for our Akka Cluster. As we moved on to use SSL encrypted communication we found that `enable-ssl=true` causes an issue in the lighthouse project startup.
The self address of the lighthouse is using `akka.tcp` as the protocol. So when the lighthouse node which is configured to use `ssl` will fail to join itself as the self address will be `akka.tcp://webcrawler@lighthouse1:4053]`.

The self address should consider if protocol is ssl encrypted or not.

**Comment by Aaronontheweb** [comment]
@JinsPeter this is going live today: https://github.com/petabridge/lighthouse/releases/tag/1.3.0
