### ISSUE TITLE
Feature: add ability to specify Akka.Cluster SplitBrainResolver strategy via environment variable

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/lighthouse#115]
We should add support for running our pre-built Lighthouse Docker images with an [Akka.Cluster SplitBrainResolver](https://getakka.net/articles/clustering/split-brain-resolver.html) - currently it's not possible to enable one of these without building a custom Docker image, and [it's considered to be a best Akka.Cluster practice to run with a consistent split brain configuration available on all cluster nodes](https://petabridge.com/blog/proper-care-of-akkadotnet-clusters/).

Therefore, we should add an ability to configure this via an environment variable:

`SPLIT_BRAIN_STRATEGY=none|keep-majority|keep-oldest|static-quorum|keep-referee`

Some of these strategies, such as static quorum and keep-referee, are going to require additional environment variables to support their mandatory parameters (quorum size and referee address, respectively.)

We should add these to the next release of Lighthouse and to the Lighthouse documentation.

The default value in Lighthouse should be `keep-majority`

**Comment by nagytech** [comment]
As shown in the image below, the docker image uses the `keep-majority` strategy by default.

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/8542033/72198963-31ddba00-3489-11ea-8c1d-48c7bee91d97.png">
