### ISSUE TITLE
pbm fails to run within the the latest docker image

### ISSUE THREAD

**Issue by rafd123** [petabridge/lighthouse#151]
As of this writing, the latest docker image is 1.3.2.

**Repro**
`docker run --rm -it petabridge/lighthouse:1.3.2 pbm`

**Expected Result**
`pbm` enters repl mode

**Actual result**
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
command terminated with exit code 150
```

**Additional Info**
I believe this commit is the root cause: https://github.com/petabridge/lighthouse/commit/614637537ea73bc36b13559175e3e42e3b464880#diff-979645effab0d0c3e101310d4a0730e8

Per the commit comments: `* runtime needs to stay at .net core 2.1`

**Comment by Aaronontheweb** [comment]
@rafd123 looks like you're right - we'll look into this and patch it.

**Comment by Aaronontheweb** [comment]
Please update to v1.3.3 https://github.com/petabridge/lighthouse/releases/tag/1.3.3

**Comment by rafd123** [comment]
Thanks for the quick turnaround, y'all! 🎉
