### ISSUE TITLE
Need to describe how to avoid DistributedPubSub serializer issues in README

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/lighthouse#179]
To avoid issues with `DistributedPubSub` trying to message lighthouse, we need to add some details to the README about how to avoid that

**Comment by simonlaroche** [comment]
Hi Aaron, our logs in lighthouse our filled with serialization errors for cluster metrics (6), distributed pub sub (9) and container serialization (10).

How can we fix this?

**Comment by wesselkranenborg** [comment]
This would indeed be very helpful.
