### ISSUE TITLE
Project crash after update to Helios 2.1.1

### ISSUE THREAD

**Issue by Caldas** [petabridge/lighthouse#18]
After upgrade Lighthouse to use **Helios v2.1.1** the following error crash the project:

![image](https://cloud.githubusercontent.com/assets/938045/15862789/1a38605a-2ca7-11e6-8962-0a3ca00fe8d4.png)

**Comment by Aaronontheweb** [comment]
@Caldas the current stable versions of Akka.NET were all compiled to work against Helios 1.4.1. We bumped the major version number in Helios to signal that there are *breaking API changes*. We'll be releasing Akka.NET 1.1 on June 14th which will include Helios 2.x out of the box.

**Comment by Caldas** [comment]
@Aaronontheweb now that **Akka 1.1** was released any chance you take a look at PRs here

- [ ] Using Wire Serializer With Lighthouse https://github.com/petabridge/lighthouse/pull/17
- [ ] Upgraded to Akka 1.1 https://github.com/petabridge/lighthouse/pull/19

**Comment by Aaronontheweb** [comment]
1.1.1 upgrade is finished; as for Wire serializer that PR needs to be rebased

**Comment by contactsamie** [comment]
@Aaronontheweb @Caldas , PR Closed . Fresh PR from base here #20
