### ISSUE TITLE
LighthouseService not started until LighthouseDiscoveryService removed

### ISSUE THREAD

**Issue by jameswilddev** [petabridge/lighthouse#31]
Hello!

I recently updated my local clone of Lighthouse to the latest version from a clone taken at 17:07 on the 21st of June.  However, it no longer seems to start.

I get a TargetInvocationException until I replace the "+" in the BaseAddress configuration property with "localhost".

After correcting this, an error isn't shown, but the seed node does not seem to be configured.  Setting breakpoints in Program.cs, LighthouseService is never started, only LighthouseDiscoveryService (new?).  Commenting out the configuration of LighthouseDiscoveryService causes LighthouseService to be started (LighthouseHostFactory.LaunchLighthouse is now called).

This might be related to my use of IIS Express rather than full IIS if you are testing on full IIS.

Thanks!

**Comment by Aaronontheweb** [comment]
Thanks, we'll look into it! Do you have a stacktrace you can share?

**Comment by Aaronontheweb** [comment]
@jameswilddev we've reverted for now - give re-clone and give that a try again

**Comment by jameswilddev** [comment]
Hello again!  I've just pulled the latest version and it works without modifications now; I'm also getting console output again which I couldn't get working myself.

Thanks!
