### ISSUE TITLE
support for deploying on linux

### ISSUE THREAD

**Issue by TonyAbell** [petabridge/lighthouse#7]
Right now, its setup to install using a Windows Service.  There should be an option to create a Linux daemon similar to [Service Stack](https://github.com/ServiceStack/ServiceStack/wiki/Run-ServiceStack-as-a-daemon-on-Linux)

**Comment by janaka** [comment]
+1

**Comment by kostrse** [comment]
+1 systemd

**Comment by alfredherr** [comment]
This would be greatly appreciated.

**Comment by Aaronontheweb** [comment]
Accomplished this via the official [Lighthouse Docker images](https://hub.docker.com/r/petabridge/lighthouse), which we're working on updating now.
